apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmdemo-nodejs
  labels:
    app: helmdemo-nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helmdemo-nodejs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helmdemo-nodejs
    spec:
      containers:
      - image: {{ .Values.nodejs.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: helmdemo-nodejs
        ports:
        - containerPort: 3000
          protocol: TCP
